#! /bin/bash

BasicTest User "Bob Normal\n33\n555000555\n22 Some Road\n"
BasicTest Monsters "Unknown\n100\n(2,0)\n2"
BasicTest List "44\n33\n44\n33\n0"
BasicTest DeepSet "3"
BasicTest Complex "3 + 4i"
BasicTest Rational "8/16\n1/4\n13/20\n"
BasicTest Plugins "Hello World"
BasicTest Inheritance "Vroom vroom!\nMy top speed is: 200\nVroom vroom!\nMy top speed is: 0"
BasicTest Methods "4\n5"
BasicTest Something "number 4\ntext hello\n0\ns is not a number"
BasicTest StringArray "Oranges\nFruit"
BasicTest ListLiteral "2"
BasicTest EmptyType "nothing"
